arch-obj-$(CONFIG_SOFTMMU) += machine.o monitor.o
arch-obj-y += translate.o helper.o cpu.o
arch-obj-y += fop_helper.o cc_helper.o win_helper.o mmu_helper.o ldst_helper.o
arch-obj-$(TARGET_SPARC) += int32_helper.o
arch-obj-$(TARGET_SPARC64) += int64_helper.o
arch-obj-$(TARGET_SPARC64) += vis_helper.o
arch-obj-y += gdbstub.o
