arch-obj-y += xtensa-semi.o
arch-obj-y += core-dc232b.o
arch-obj-y += core-dc233c.o
arch-obj-y += core-fsf.o
arch-obj-$(CONFIG_SOFTMMU) += monitor.o
arch-obj-y += translate.o op_helper.o helper.o cpu.o
arch-obj-y += gdbstub.o
