arch-obj-y += cpu-models.o
arch-obj-y += translate.o
ifeq ($(CONFIG_SOFTMMU),y)
arch-obj-y += machine.o mmu_helper.o mmu-hash32.o monitor.o
arch-obj-$(TARGET_PPC64) += mmu-hash64.o arch_dump.o
endif
arch-obj-$(CONFIG_KVM) += kvm.o
arch-obj-$(call lnot,$(CONFIG_KVM)) += kvm-stub.o
arch-obj-y += dfp_helper.o
arch-obj-y += excp_helper.o
arch-obj-y += fpu_helper.o
arch-obj-y += int_helper.o
arch-obj-y += timebase_helper.o
arch-obj-y += misc_helper.o
arch-obj-y += mem_helper.o
arch-obj-$(CONFIG_USER_ONLY) += user_only_helper.o
arch-obj-y += gdbstub.o
