arch-obj-y += translate.o dsp_helper.o op_helper.o lmi_helper.o helper.o cpu.o
arch-obj-y += gdbstub.o msa_helper.o mips-semi.o
arch-obj-$(CONFIG_SOFTMMU) += machine.o
arch-obj-$(CONFIG_KVM) += kvm.o
