arch-obj-y += translate.o helper.o cpu.o interrupt.o
arch-obj-y += int_helper.o fpu_helper.o cc_helper.o mem_helper.o misc_helper.o
arch-obj-y += gdbstub.o
arch-obj-$(CONFIG_SOFTMMU) += machine.o ioinst.o arch_dump.o mmu_helper.o
arch-obj-$(CONFIG_KVM) += kvm.o
