arch-obj-$(CONFIG_SOFTMMU) += machine.o
arch-obj-y += cpu.o exception.o interrupt.o mmu.o translate.o
arch-obj-y += exception_helper.o fpu_helper.o int_helper.o \
         interrupt_helper.o mmu_helper.o sys_helper.o
arch-obj-y += gdbstub.o
